_target_: common.dataset.Masked_CT_Dataset
fold_path: "/app/MAR/data/123_fold.json"
#"/app/MAR/HN-CT-MAR/codes/final_all_data_1_fold.json"
dataset_type: "Train"
# torch_type: float
data_type: npy
infer: False