_target_: core.module.baseline.MAR
defaults:
  - _self_
  - model: fusionnet
  - dataset: baseline

criterion:
  _target_: common.loss.MSE_SSIM_Loss
  ssim_rate: 0.1
  device: "cuda:3"

# optimizer:
#   _target_: torch.optim.Adam
#   lr: 0.0001

optimizer:
  _target_: torch.optim.Adam
  lr: 0.001

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: 300
  eta_min: 0.00001
  
shuffle:
  train: True
  validation: False
  test: False
  predict: False

save_output_only: False
test_save_path: "./output"
batch_size: 16
num_worker: 8
save_path: Null