_target_: core.module.baseline.MAR

defaults:
  - model: fusionnet
  - dataset: baseline

criterion:
  _target_: common.loss.MSE_SSIM_Loss
  ssim_rate: 0.1
  device: "cuda:3"

optimizer:
  _target_: torch.optim.Adam
  lr: 0.0001

save_output_only: False
test_save_path: "./output"
batch_size: 1
num_worker: 8
save_path: ??